provider:
  name: faas
  gateway: http://localhost:8080

functions:
  # darknet:
  #   lang: Dockerfile
  #   handler: ./darknet
  #   image: yogeek/faas-darknet
  #   environment:
  #     read_timeout: 120
  #     write_timeout: 120

  # yolo:
  #   lang: Dockerfile
  #   handler: ./yolo
  #   image: yogeek/faas-yolo:2.0
  #   environment:
  #     read_timeout: 120
  #     write_timeout: 120

  yolo:
    lang: Dockerfile
    handler: ./yolo-minio
    image: yogeek/faas-yolo-minio
    environment:
      read_timeout: 120
      write_timeout: 120
    environment_file:
      - credentials.yml

  # nothotdog:
  #   lang: Dockerfile
  #   handler: ./nothotdog
  #   image: yogeek/faas-nothotdog
  #   environment:
  #     read_timeout: 60
  #     write_timeout: 60
