provider:
  name: faas
  gateway: http://172.28.128.4:8080

functions:
  darknet:
    lang: Dockerfile
    handler: ./darknet
    image: yogeek/faas-darknet
    environment:
      read_timeout: 120
      write_timeout: 120

  darknet:
    lang: Dockerfile
    handler: ./yolo
    image: yogeek/faas-yolo
    environment:
      read_timeout: 120
      write_timeout: 120

  nothotdog:
    lang: Dockerfile
    handler: ./nothotdog
    image: yogeek/faas-nothotdog
    environment:
      read_timeout: 60
      write_timeout: 60
