provider:
  name: faas
  gateway: http://localhost:8080

functions:
  darknet:
    lang: Dockerfile
    handler: ./darknet
    image: yogeek/faas-darknet
    environment:
      read_timeout: 60
      write_timeout: 60

  nothotdog:
    lang: Dockerfile
    handler: ./nothotdog
    image: yogeek/faas-nothotdog
    environment:
      read_timeout: 60
      write_timeout: 60
