provider:
  name: faas
  gateway: http://localhost:8080

functions:
  darknet:
    lang: Dockerfile
    handler: ./darknet
    image: yogeek/darknet
    environment:
      read_timeout: 60
      write_timeout: 60
