version: "3.2"
services:
    gateway:
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - 8080:8080
        image: functions/gateway:0.6.9
        networks:
            - functions
        environment:
            dnsrr: "true"  # Temporarily use dnsrr in place of VIP while issue persists on PWD
            read_timeout: 120
            write_timeout: 120
        deploy:
            # resources:
            #     limits:
            #         memory: 50M
            #     reservations:
            #         memory: 20M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 20
                window: 380s
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'
    # End

    # Start monitoring

    prometheus:
        image: functions/prometheus:latest  # autobuild from Dockerfile in repo.
        command: "-config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -storage.local.memory-chunks=10000 --alertmanager.url=http://alertmanager:9093"
        ports:
            - 9090:9090
        depends_on:
            - gateway
            - alertmanager
        environment:
            no_proxy: "gateway"
        networks:
            - functions
        deploy:
            resources:
                limits:
                    memory: 500M
                reservations:
                    memory: 200M
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'

    alertmanager:
        image: functions/alertmanager:latest    # autobuild from Dockerfile in repo.
        environment:
            no_proxy: "gateway"
        command:
            - '-config.file=/alertmanager.yml'
        networks:
            - functions
        ports:
            - 9093:9093
        deploy:
            resources:
                limits:
                    memory: 50M
                reservations:
                    memory: 20M
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'

    grafana:
        image: grafana/grafana:latest
        environment:
            no_proxy: "gateway"
        ports:
              - "3000:3000"
        networks:
            - functions
        depends_on:
            - gateway
        deploy:
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'

    minio:
        image: minio/minio
        volumes:
            - minio-data:/data
            - minio-config:/root/.minio
        ports:
            - 9000:9000
        networks:
            - functions
        environment:
            MINIO_ACCESS_KEY: 671A6QYAL6D7QF1G2EF8
            MINIO_SECRET_KEY: ZXQsO6ak1zSzknHPmv1H8fxb7hHNvg/csiaGnQYX
            no_proxy: "gateway"
            https_proxy: $https_proxy
        deploy:
            restart_policy:
                condition: any
                delay: 10s
                max_attempts: 10
                window: 60s
            placement:
                constraints:
                    - 'node.platform.os == linux'
        command: server /data
    
    filelistener:
        image: yogeek/filelistener:latest
        build:
            context: ./filelistener
        depends_on:
            - gateway
        networks:
            - functions
        environment:
            minio_hostname: "minio:9000"
            minio_access_key: "671A6QYAL6D7QF1G2EF8"
            minio_secret_key: "ZXQsO6ak1zSzknHPmv1H8fxb7hHNvg/csiaGnQYX"
            bucket_input: "input"
            no_proxy: "gateway"
            https_proxy: $https_proxy
        deploy:
            placement:
                constraints:
                    - 'node.platform.os == linux'

volumes:
  minio-data:
  minio-config:

networks:
    functions:
        driver: overlay
        attachable: true
