version: "3.2"
services:

    grafana:
        image: grafana/grafana:latest
        environment:
            no_proxy: "gateway"
        ports:
              - "3000:3000"
        networks:
            - functions
        depends_on:
            - gateway
        deploy:
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'

    minio:
        image: minio/minio
        volumes:
            - minio-data:/data
            - minio-config:/root/.minio
        ports:
            - 9000:9000
        networks:
            - functions
        environment:
            MINIO_ACCESS_KEY: 671A6QYAL6D7QF1G2EF8
            MINIO_SECRET_KEY: ZXQsO6ak1zSzknHPmv1H8fxb7hHNvg/csiaGnQYX
            no_proxy: "gateway"
            https_proxy: $https_proxy
        deploy:
            restart_policy:
                condition: any
                delay: 10s
                max_attempts: 10
                window: 60s
            placement:
                constraints:
                    - 'node.platform.os == linux'
        command: server /data
    

    filelistener:
        image: yogeek/filelistener:latest
        build:
            context: ./filelistener
        depends_on:
            - gateway
        networks:
            - functions
        environment:
            minio_hostname: "minio:9000"
            minio_access_key: "671A6QYAL6D7QF1G2EF8"
            minio_secret_key: "ZXQsO6ak1zSzknHPmv1H8fxb7hHNvg/csiaGnQYX"
            bucket_input: "input"
            no_proxy: "gateway"
            https_proxy: $https_proxy
        deploy:
            placement:
                constraints:
                    - 'node.platform.os == linux'

volumes:
  minio-data:
  minio-config:

networks:
    functions:
        driver: overlay
        attachable: true
